### ISSUE TITLE
Wrong Language selected when adding Subtitles regarding name, also not Enabled

### ISSUE THREAD

**Issue by Morku** [staxrip/staxrip#1174]
**Describe the bug**
When adding a Subtitle (in my case srt) with the Language in it's name, the Language is preselected in StaxRip and of course are Enabled.

With 2.31 this feature broke. Staxrip is selecting randomly a Language and the added subtitle is not Enabled. I have to correct that for any added Subtitle.

**How to reproduce the issue**

1. Click Container Options
2. Add e.g. "English.srt"
3. Language should be "English", but it's not.

2.31.0 with the issue:

https://github.com/staxrip/staxrip/assets/6276915/4ca061c3-77b0-47ce-b9d3-f6cda0d1f861

To compare 2.30.0 where everything is fine:

https://github.com/staxrip/staxrip/assets/6276915/8c7a9953-2f35-4b50-99af-44451b9c476f

**Provide information**

I have tested StaxRip 2.31.0 and 2.30.0 in a fresh, clean installation with new Setting. The issue already is without any modification.
Use Windows 11 Version 22H2 Build 22621.2861
Both versions have the following Subtitle settings (unmodified):

![grafik](https://github.com/staxrip/staxrip/assets/6276915/04097d15-2f6c-42bf-922e-711d66d8fcce)

**Comment by Dendraspis** [comment]
Basically a copy of my response on Discord:
The recognition of for example `English.srt` fails due to the change of the languages and codes. It should work with `English [en].srt` or `en-US.srt`, but I will optimise it for the next release..

**Comment by darkcity87** [comment]
Language changed English to German
```
General
Unique ID                   : 73903908483035247740087116833920665574 (0x379960025323FE989158979DE83C47E6)
Complete name               : C:\a\test.mkv
Format                      : Matroska
Format version              : Version 4
File size                   : 1.33 GiB
Duration                    : 28 min 32 s
Overall bit rate mode       : Variable
Overall bit rate            : 6 675 kb/s
Frame rate                  : 23.976 FPS
Encoded date                : 2021-03-04 10:01:50 UTC
Writing application         : mkvmerge v53.0.0 ('Fool's Gold') 64-bit
Writing library             : libebml v1.4.1 + libmatroska v1.6.2
Cover                       : Yes
Attachments                 : small_cover.jpg / small_cover_land.jpg / cover.jpg / cover_land.jpg

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : Main@L4
Format settings             : CABAC / 3 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 3 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 28 min 32 s
Bit rate mode               : Variable
Bit rate                    : 5 620 kb/s
Maximum bit rate            : 8 430 kb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.113
Stream size                 : 1.07 GiB (81%)
Writing library             : x264 core 148 r2722 1b0121b
Encoding settings           : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x1:0x111 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=8 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / stitchable=1 / constrained_intra=0 / bframes=2 / b_pyramid=0 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=0 / intra_refresh=0 / rc_lookahead=48 / rc=2pass / mbtree=1 / bitrate=5620 / ratetol=1.0 / qcomp=0.50 / qpmin=6 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=8430 / vbv_bufsize=11240 / nal_hrd=vbr / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default                     : Yes
Forced                      : No

Audio #1
ID                          : 2
Format                      : E-AC-3
Format/Info                 : Enhanced AC-3
Commercial name             : Dolby Digital Plus
Codec ID                    : A_EAC3
Duration                    : 28 min 32 s
Bit rate mode               : Constant
Bit rate                    : 640 kb/s
Channel(s)                  : 6 channels
Channel layout              : L R C LFE Ls Rs
Sampling rate               : 48.0 kHz
Frame rate                  : 31.250 FPS (1536 SPF)
Compression mode            : Lossy
Stream size                 : 131 MiB (10%)
Language                    : Japanese
Service kind                : Complete Main
Default                     : Yes
Forced                      : No

Audio #2
ID                          : 3
Format                      : E-AC-3
Format/Info                 : Enhanced AC-3
Commercial name             : Dolby Digital Plus
Codec ID                    : A_EAC3
Duration                    : 28 min 32 s
Bit rate mode               : Constant
Bit rate                    : 640 kb/s
Channel(s)                  : 6 channels
Channel layout              : L R C LFE Ls Rs
Sampling rate               : 48.0 kHz
Frame rate                  : 31.250 FPS (1536 SPF)
Compression mode            : Lossy
Stream size                 : 131 MiB (10%)
Language                    : English
Service kind                : Complete Main
Default                     : No
Forced                      : No

Text #1
ID                          : 4
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 3 s
Bit rate                    : 61 b/s
Frame rate                  : 0.281 FPS
Count of elements           : 456
Stream size                 : 12.1 KiB (0%)
Title                       : SDH
Language                    : English
Default                     : Yes
Forced                      : No

Text #2
ID                          : 5
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 25 s
Bit rate                    : 0 b/s
Frame rate                  : 0.007 FPS
Count of elements           : 11
Stream size                 : 164 Bytes (0%)
Title                       : Forced
Language                    : English
Default                     : No
Forced                      : No

Text #3
ID                          : 6
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 79 b/s
Frame rate                  : 0.189 FPS
Count of elements           : 311
Stream size                 : 15.9 KiB (0%)
Language                    : Arabic
Default                     : No
Forced                      : No

Text #4
ID                          : 7
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 42 b/s
Frame rate                  : 0.185 FPS
Count of elements           : 304
Stream size                 : 8.53 KiB (0%)
Language                    : Czech
Default                     : No
Forced                      : No

Text #5
ID                          : 8
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 41 b/s
Frame rate                  : 0.177 FPS
Count of elements           : 291
Stream size                 : 8.39 KiB (0%)
Language                    : Danish
Default                     : No
Forced                      : No

Text #6
ID                          : 9
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 44 b/s
Frame rate                  : 0.182 FPS
Count of elements           : 299
Stream size                 : 8.96 KiB (0%)
Language                    : German
Default                     : No
Forced                      : No

Text #7
ID                          : 10
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 75 b/s
Frame rate                  : 0.192 FPS
Count of elements           : 316
Stream size                 : 15.1 KiB (0%)
Language                    : Greek
Default                     : No
Forced                      : No

Text #8
ID                          : 11
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 43 b/s
Frame rate                  : 0.180 FPS
Count of elements           : 296
Stream size                 : 8.64 KiB (0%)
Language                    : Spanish
Default                     : No
Forced                      : No

Text #9
ID                          : 12
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 44 b/s
Frame rate                  : 0.190 FPS
Count of elements           : 312
Stream size                 : 8.86 KiB (0%)
Language                    : Spanish
Default                     : No
Forced                      : No

Text #10
ID                          : 13
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 44 b/s
Frame rate                  : 0.168 FPS
Count of elements           : 277
Stream size                 : 8.84 KiB (0%)
Language                    : Finnish
Default                     : No
Forced                      : No

Text #11
ID                          : 14
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 42 b/s
Frame rate                  : 0.189 FPS
Count of elements           : 310
Stream size                 : 8.47 KiB (0%)
Language                    : French
Default                     : No
Forced                      : No

Text #12
ID                          : 15
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 75 b/s
Frame rate                  : 0.198 FPS
Count of elements           : 326
Stream size                 : 15.1 KiB (0%)
Language                    : Hebrew
Default                     : No
Forced                      : No

Text #13
ID                          : 16
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 26 s
Bit rate                    : 40 b/s
Frame rate                  : 0.185 FPS
Count of elements           : 305
Stream size                 : 8.21 KiB (0%)
Language                    : Croatian
Default                     : No
Forced                      : No

Text #14
ID                          : 17
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 27 s
Bit rate                    : 45 b/s
Frame rate                  : 0.185 FPS
Count of elements           : 305
Stream size                 : 9.12 KiB (0%)
Language                    : Hungarian
Default                     : No
Forced                      : No

Text #15
ID                          : 18
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 26 s
Bit rate                    : 42 b/s
Frame rate                  : 0.187 FPS
Count of elements           : 308
Stream size                 : 8.46 KiB (0%)
Language                    : Indonesian
Default                     : No
Forced                      : No

Text #16
ID                          : 19
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 27 s
Bit rate                    : 42 b/s
Frame rate                  : 0.182 FPS
Count of elements           : 299
Stream size                 : 8.62 KiB (0%)
Language                    : Italian
Default                     : No
Forced                      : No

Text #17
ID                          : 20
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 47 b/s
Frame rate                  : 0.220 FPS
Count of elements           : 362
Stream size                 : 9.63 KiB (0%)
Language                    : Japanese
Default                     : No
Forced                      : No

Text #18
ID                          : 21
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 59 b/s
Frame rate                  : 0.195 FPS
Count of elements           : 320
Stream size                 : 11.9 KiB (0%)
Language                    : Korean
Default                     : No
Forced                      : No

Text #19
ID                          : 22
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 43 b/s
Frame rate                  : 0.193 FPS
Count of elements           : 317
Stream size                 : 8.74 KiB (0%)
Language                    : Malay
Default                     : No
Forced                      : No

Text #20
ID                          : 23
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 25 s
Bit rate                    : 43 b/s
Frame rate                  : 0.165 FPS
Count of elements           : 271
Stream size                 : 8.78 KiB (0%)
Language                    : Norwegian Bokmal
Default                     : No
Forced                      : No

Text #21
ID                          : 24
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 28 s
Bit rate                    : 39 b/s
Frame rate                  : 0.168 FPS
Count of elements           : 277
Stream size                 : 7.97 KiB (0%)
Language                    : Dutch
Default                     : No
Forced                      : No

Text #22
ID                          : 25
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 39 b/s
Frame rate                  : 0.181 FPS
Count of elements           : 297
Stream size                 : 7.95 KiB (0%)
Language                    : Polish
Default                     : No
Forced                      : No

Text #23
ID                          : 26
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 43 b/s
Frame rate                  : 0.187 FPS
Count of elements           : 308
Stream size                 : 8.82 KiB (0%)
Title                       : Brasil
Language                    : Portuguese
Default                     : No
Forced                      : No

Text #24
ID                          : 27
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 43 b/s
Frame rate                  : 0.188 FPS
Count of elements           : 309
Stream size                 : 8.75 KiB (0%)
Language                    : Portuguese
Default                     : No
Forced                      : No

Text #25
ID                          : 28
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 26 min 57 s
Bit rate                    : 49 b/s
Frame rate                  : 0.185 FPS
Count of elements           : 299
Stream size                 : 9.78 KiB (0%)
Language                    : Romanian
Default                     : No
Forced                      : No

Text #26
ID                          : 29
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 26 s
Bit rate                    : 75 b/s
Frame rate                  : 0.192 FPS
Count of elements           : 316
Stream size                 : 15.1 KiB (0%)
Language                    : Russian
Default                     : No
Forced                      : No

Text #27
ID                          : 30
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 23 s
Bit rate                    : 44 b/s
Frame rate                  : 0.172 FPS
Count of elements           : 282
Stream size                 : 8.88 KiB (0%)
Language                    : Swedish
Default                     : No
Forced                      : No

Text #28
ID                          : 31
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 123 b/s
Frame rate                  : 0.190 FPS
Count of elements           : 312
Stream size                 : 24.8 KiB (0%)
Language                    : Thai
Default                     : No
Forced                      : No

Text #29
ID                          : 32
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 44 b/s
Frame rate                  : 0.179 FPS
Count of elements           : 294
Stream size                 : 9.00 KiB (0%)
Language                    : Turkish
Default                     : No
Forced                      : No

Text #30
ID                          : 33
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 61 b/s
Frame rate                  : 0.185 FPS
Count of elements           : 304
Stream size                 : 12.2 KiB (0%)
Language                    : Vietnamese
Default                     : No
Forced                      : No

Text #31
ID                          : 34
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 47 b/s
Frame rate                  : 0.199 FPS
Count of elements           : 328
Stream size                 : 9.58 KiB (0%)
Title                       : Simplified
Language                    : Chinese
Default                     : No
Forced                      : No

Text #32
ID                          : 35
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 24 s
Bit rate                    : 52 b/s
Frame rate                  : 0.216 FPS
Count of elements           : 355
Stream size                 : 10.5 KiB (0%)
Title                       : Traditional
Language                    : Chinese
Default                     : No
Forced                      : No
```
![Ekran görüntüsü 2024-01-05 181751](https://github.com/staxrip/staxrip/assets/12258051/75d30454-47f0-48e3-8222-e3e50900ae26)
![Ekran görüntüsü 2024-01-05 182044](https://github.com/staxrip/staxrip/assets/12258051/b4c4df99-4701-49b5-a81c-3c420ddfbe27)

**Comment by darkcity87** [comment]
from another file
dont recognize Traditional (Hong Kong)

```
Text #18
ID                          : 21
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 12 min 44 s
Bit rate                    : 21 b/s
Frame rate                  : 0.098 FPS
Count of elements           : 75
Stream size                 : 2.01 KiB (0%)
Title                       : Traditional (Hong Kong)
Language                    : Chinese-Hant-HK
Default                     : No
Forced                      : No
```

![Ekran görüntüsü 2024-01-05 185059](https://github.com/staxrip/staxrip/assets/12258051/b0ab5529-e4c4-44e5-8112-9881804e7909)
![Ekran görüntüsü 2024-01-05 185141](https://github.com/staxrip/staxrip/assets/12258051/838d98b5-b999-4288-9173-dc4e60b84b1e)

**Comment by darkcity87** [comment]
@Dendraspis 
Did you fix about no passthrough ''default'' flag from source to output?
You can see from my first comment eng subtitle is named ''SDH'' and ''Default'' flagged but Container page shows file name ''SDH_default'' and default flag not selected.

**Comment by Dendraspis** [comment]
1. Please stop pinging me, it won't make me look earlier.
2. No, I didn't as this works as intended. If it doesn't work for you, you're setting in `Options » Subtitles » Default Subtitle` might be wrong, maybe `None`.

**Comment by darkcity87** [comment]
1. Sorry about that i didnt mean anythink.
2. Thanks i didnt know that setting i change to `Default` its fix my issue. Shipped template setted `None` i never change before.
3. it still didnt fix track name issue default subtitle `SDH` changed `SDH_default`

**Comment by Dendraspis** [comment]
1. No problem
2. Yeah, `Default` is the right one for you as it reads the `_default` pattern from the source file. Just to mention, `None` was the default value for at least 2 years.  
3. I don't understand what you mean. Can you give me an example?

**Comment by darkcity87** [comment]
title name `SDH`
```
Text #1
ID                          : 4
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 27 min 3 s
Bit rate                    : 61 b/s
Frame rate                  : 0.281 FPS
Count of elements           : 456
Stream size                 : 12.1 KiB (0%)
Title                       : SDH  <<<------------<<<<
Language                    : English
Default                     : Yes
Forced                      : No
```
![Ekran görüntüsü 2024-01-06 001951](https://github.com/staxrip/staxrip/assets/12258051/9f0a5f03-37af-42b3-ad67-a4a1b43cc6f6)

**Comment by Dendraspis** [comment]
That is already fixed for the next release.

**Comment by darkcity87** [comment]
Ok thanks

**Comment by zash13x** [comment]
Experiencing the exact same problem with subtitles in v2.31.0.

**Comment by Morku** [comment]
Can you please check the issue with 2.32? It still does not recognize the Language when adding Subtitles like it did with 2.30 and previous. It's now just Undeterminded.
I also wouldn't call this a naming issue, because when I add a original SUP Subtitle extracted with eac3to without changing the file, the name is not recognized.

https://github.com/staxrip/staxrip/assets/6276915/c186af79-4a41-44a8-94b6-bcf2cee27d92

**Comment by Dendraspis** [comment]
Well, I fixed it and while fixing and enhancing another part of the problem, I broke it again.  🤦‍♂️ 
Thanks for bringing that up.

Can you please verify, that this fix works now as it should?
[StaxRip_v2.32.1.zip](https://github.com/staxrip/staxrip/files/13873274/StaxRip_v2.32.1.zip)  (totally compatible with `v2.32.0`)

**Comment by Morku** [comment]
This is working fine, great :) Tested again with German and English.

**Comment by Dendraspis** [comment]
Thank you, so closed again  😬

**Comment by darkcity87** [comment]
Language changed Norwegian to Ndebele

Source
```
Text #18
ID                          : 23
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 23 min 38 s
Bit rate                    : 59 b/s
Frame rate                  : 0.240 FPS
Count of elements           : 340
Stream size                 : 10.4 KiB (0%)
Language                    : Norwegian
Default                     : No
Forced                      : No
```

Temp file
`ID18_[nr]`

Output
```
Text #18
ID                          : 21
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 23 min 38 s
Bit rate                    : 59 b/s
Frame rate                  : 0.240 FPS
Count of elements           : 340
Stream size                 : 10.4 KiB (0%)
Language                    : Ndebele
Default                     : No
Forced                      : No
```
