### ISSUE TITLE
staxrip 2.36 crashes in attempt to encode av1 stream

### ISSUE THREAD

**Issue by arctus256** [staxrip/staxrip#1261]
2.36
Crashes when rigaya's av1 encoders (nvenc|qsvenc) are used to encode the stream.

Log snippet:

```
Dynamic HDR10     E:\multimedia\movie\_nvenc _crash\video_temp\HDRDVmetadata_L5.json
dovi rpu       E:\multimedia\movie\_nvenc _crash\video_temp\HDRDVmetadata_Cropped.rpu
Others         mv:auto 
bitstream: Adding dovi rpu not supported in AV1 encoding.
bitstream: Adding dovi rpu not supported in AV1 encoding.
Error occurred in ProcessOutput: 20
bitstream: Adding dovi rpu not supported in AV1 encoding.
Error occurred in ProcessOutput: 20
```

To reproduce this kind of error it is just enough to use defaults of mentioned encoders.

Most likely the crash is related to these encoder options:
[1] --dhdr10-info <string> [HEVC, AV1]
[2] --dhdr10-info copy [HEVC, AV1]
[3] --dolby-vision-profile <float>
[4] --dolby-vision-rpu <string>

StaxRip does not crash when only [2] is provided to cli. However the output file is far from being perfect.
DoVi data is misaligned. DAR is applied to DoVi rather than video itself. As the result video looks sqeezed within crop boundaries, like the crop was applied twiece:
1: just to DoVi
2: again (respecting ratio) to final result

**Comment by Dendraspis** [comment]
Thanks for the detailed report.

The crash should be related to the fact, that your source file does have Dolby Vision metadata, but no HDR10+ metadata. StaxRip incorrectly loads the wrong file instead, meaning `E:\multimedia\movie\_nvenc _crash\video_temp\HDRDVmetadata_L5.json`.

After opening the source file or before adding the job, go to the encoder settings and delete the path at `HDR10 Info file`, which should be the mentioned `E:\multimedia\movie\_nvenc _crash\video_temp\HDRDVmetadata_L5.json`.

After that you should be able to run the encode.

The problem is already solved for the next release...

**Comment by arctus256** [comment]
Thanks for solution... and there is "but" as always ;) Still does not work for me. I removed the path to *json file. It resulted in already mentioned crash

```
bitstream: Adding dovi rpu not supported in AV1 encoding.
bitstream: Adding dovi rpu not supported in AV1 encoding.
Error occurred in ProcessOutput: 20
```

Set DV profile to undefined (hopefully encoder would use something suitable). Same result -> crash.
Finally the path to RPU file was removed. No crash and no success. Output file is messed again. 

From my point of view there should be passthrough option when encoding hevc to av1. Alternatively, all GUI options/prompts need to be left/set to defaults.

Is there a chance that you could provide link to test build?

**Comment by arctus256** [comment]
I sort of got it working. On the main screen under AVS filter section, I switched off Crop. Then, in the encoder... path to *json file remained untouched. DV path was cleaned, to prevent crashing. The resulting file is is properly encoded without misaligned colors... except it wasn't cropped and it's still original height/width.

**Comment by arctus256** [comment]
I am sorry for not being specific enough. My bad. Colors in output file were misaligned, and yes I am very sure I cleared out HDR10 Info file prompt :) Here is the screenshot of settings used for conversion as well as the example of misaligned colors. The rest of the options used for this particular conversion is also visible in the screenshot. 

![01  StaxRip VUI encoder settings](https://github.com/staxrip/staxrip/assets/109520722/5dbf20c9-0f11-4ff1-b205-6509b423c683)
![02-Misaligned colors](https://github.com/staxrip/staxrip/assets/109520722/659e45d8-3934-449d-9d4c-7375344a937c)

Besides I have just realised that there are some minor discrepancies between content of the *json file and the "global" crop set in main form.

*json:
```
{
  "crop": true,
  "presets": [
    {
      "id": 0,
      "left": 0,
      "right": 0,
      "top": 276,
      "bottom": 277
    }
  ],
  "edits": {
    "0-166427": 0
  }
}
```

"Global" crop values: 
`--crop 0,276,0276`

**Comment by Dendraspis** [comment]
So it seems that you have used the Hardware Crop or Hardware Decoder. Is that correct?
Could you please share the log file of that encode?

**Comment by arctus256** [comment]
You are right. Majority of the time I let hardware to do all the hard work. It happened that in few rare/edge cases hardware decoder could not cope with some stream. The attached log was mangled by me by removal all unnecessary white noise [in form of text substreams] to reduce the size... and also mkvmerge cli command. I think this is out of the scope of the investigated issue. I marked all places where removal was applied with [...].
[video_new_staxrip.log](https://github.com/staxrip/staxrip/files/14487139/video_new_staxrip.log)

**Comment by Dendraspis** [comment]
Can you do me a favor?

Please run the job again but without specifying `--dolby-vision-profile 8.1`. There is no RPU file stated, but just to make sure this parameter does not break the outcome. It would be possible, that this triggers `--dolby-vision-rpu copy`, which could explain this issue.

**Comment by arctus256** [comment]
I did as per your suggestion and removed dolby profile. No difference. The colors are still misaligned. 

On the good side, I finally nailed the problem :) All the issues described in this thread are related to this set of parameters given to the cli at once:
--avhw
--codec av1
--crop 0,276,0,276.
In particular crop is the one to be blamed. When removed, the colors are finally in place. 
Switching to:
--avsw
--codec av1
--crop 0,276,0,276 gave me the result I was expecting from beginning.

Summarizing:
[1] It is either bug or feature in nvenc when using hardware decoder causes misalignment colors
[2] there is no point in passing --dhdr10-info (copy or path to file) when dolby vision rpu is available.

Please correct me in case I am wrong in my summary statements :)

**Comment by Dendraspis** [comment]
Okay, that's great, because that would be also my conclusion in case it would not have worked. 😄 Thanks for that.

So when you use the built-in hardware decoder, the metadata seems to be transferred anyways which looks more like a bug. Not sure about [2], but it definitely has to do something with cropping and the given metadata.

But I'm glad we have found out what happened and how to solve it ... and that there is no bug in StaxRip. 😅

So I close this one. Have a nice one...

**Comment by Dendraspis** [comment]
As it turned out this issue was already known and solved in `NVEncC v7.45`:
https://github.com/rigaya/NVEnc/releases/tag/7.45

@arctus256 
So either update manually or wait for the next StaxRip release and your issue should be gone.  👍

**Comment by arctus256** [comment]
I was planning to raise the ticket tomorrow @rigayas. If it is already fixed there is nothing to be done on my side ;) It was unfortunate that so many changes popped up in so many places at the same time. It was hard to find the root cause. Thank for the great tool and you involvement :) 

BTW. If you wish I could help with testing av1 with qvsenc and/or nvenc.

**Comment by Dendraspis** [comment]
Thanks you, I appreciate your help. But unless you are not on Discord, I think it should be enough when you can check out `v2.37` next week and report any issues you may find.  🙂 

A really short btw: 
Did `NVEncC v7.45` solve your issue with the cropping?

**Comment by arctus256** [comment]
Ok. NVEncC v7.45 works for me as expected/
