### ISSUE TITLE
x265 wrong default of Hist Threshold

### ISSUE THREAD

**Issue by tkozybski** [staxrip/staxrip#441]
**Describe the bug**
In x265 0.03 is the default for --hist-threshold but when I use 0.01 in the settings, it thinks it's the default and doesn't pass the parameter.

**Expected behavior**
Change the GUI default of --hist-threshold to 0.03.

Using the 2.1.7.0 version.

**Comment by Patman86** [comment]
Yes, that's right. Official default is 0.03 😬

**Comment by 44vince44** [comment]
@tkozybski : In the mean time, don't forget you can use the custom field, type in: --hist-threshold 0.01
Until a fix is released.

**Comment by Dendraspis** [comment]
Is fixed for the next beta - and also the range that changed from 0.0-2.0 to 0.0-1.0.  ☺️ 

The default changed undocumented on 2020-06-29, so half a year ago. 🙄

**Comment by 44vince44** [comment]
@Dendraspis
-the new RANGE 0.1 to 1.0  is fixed OK
-the default handling is (meaning 0.3 will remove the switch) very OK
-the initial value of it is still set to 0.01 => **NOT OK, it should be 0.03**

**Comment by Dendraspis** [comment]
@44vince44 
Is it possible you use an old video profile or job, where `--hist-threshold` is still set to 0.01?  😉 
When you use a fresh profile/job you will see, that it works without issues.

**Comment by 44vince44** [comment]
I selected another encoder then got back to x265. When doing that it usually brings back init values!
I'm testing now with blank settings and profiles and templates

**Comment by Dendraspis** [comment]
@44vince44 
Come on, sometimes I mention issues as fixed that still don't work and you test them. So please, no "sorry"!
Thanks for the feedback and testing and ....  😊
