### ISSUE TITLE
x265 dhdr10-info disabled 

### ISSUE THREAD

**Issue by kliffgomel** [staxrip/staxrip#464]
Custom build x265 DJATOM Mod does not support --dhdr10-info option.

x265 [info]: HEVC encoder version 3.4+55+1-2e0a870f0 [DJATOM's Mod]
x265 [info]: build info [Windows][GCC 10.2.1][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: --dhdr10-info disabled. Enable HDR10_PLUS in cmake.

It would be great if support for copying hdr10+ metadata was added to staxrip when processing video with a codec that supports the transfer of this metadata.

**Comment by Dendraspis** [comment]
@DJATOM 
It would be nice, if you could enabled this feature for us.  😄

**Comment by DJATOM** [comment]
With new releases then. I'm drowning in the work right now, sorry.

**Comment by 44vince44** [comment]
@Patman86 I'm surprised of your silence... Are you drowning under work as well??? 😅

**Comment by DJATOM** [comment]
Well, trying to compile, it looks like no so easy as I thought. I'm enabling it but lib isn't linking at all.

**Comment by DJATOM** [comment]
Could you please test [x265-x64-v3.4+62-aMod-gcc10.2.1-hdr10-info.exe.zip](https://github.com/staxrip/staxrip/files/5844273/x265-x64-v3.4%2B62-aMod-gcc10.2.1-hdr10-info.exe.zip)?

**Comment by 44vince44** [comment]
Testing now

**Comment by 44vince44** [comment]
OK I'm not an expert in that matter (I dowloaded a sample file with its .json)
The  --dhdr10-info  "filename" has been taken (no error shown). I am continuing testing to compare video output and check that the data inside json has been really used, But I guess this should prove something yet : 

```
avs+ [info]: AviSynth+ 3.7.0 (r3382, 3.7, x86_64)
avs+ [info]: 1184x664 fps 24/1 i420p10 frames 0 - 1145 of 1146
raw  [info]: output file: D:\Downloads\_IDM Downloads\with HDR-10+_temp\with HDR-10+_out.hevc
x265 [info]: HEVC encoder version 3.4+62 [DJATOM's Mod]
x265 [info]: build info [Windows][GCC 10.2.1][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: Turning on repeat-headers for HDR compatibility
x265 [info]: Main 10 profile, Level-3.1 (Main tier)
x265 [info]: Thread pool created using 8 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 3 / wpp(21 rows)
x265 [warning]: Source height < 720p; disabling lookahead-slices
x265 [info]: Coding QT: max CU size, min CU size : 32 / 16
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : dia / 57 / 0 / 2
x265 [info]: Lookahead / bframes / badapt        : 5 / 3 / 0
x265 [info]: b-pyramid / weightp / weightb       : 1 / 0 / 0
x265 [info]: References / ref-limit  cu / depth  : 1 / off / off
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 1 / 0.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-30.0 / 0.60
x265 [info]: tools: rd=2 psy-rd=2.00 early-skip rskip mode=1 tmvp fast-intra
x265 [info]: tools: strong-intra-smoothing deblock dhdr10-info
avs+ [error]: LSMASHVideoSource: failed to make a frame. occurred while reading frame 97
x265 [info]: frame I:      1, Avg QP:33.94  kb/s: 1507.39 
x265 [info]: frame P:     25, Avg QP:34.68  kb/s: 750.16  
x265 [info]: frame B:     71, Avg QP:37.32  kb/s: 354.70  
x265 [info]: consecutive B-frames: 7.7% 0.0% 3.8% 88.5% 
encoded 97 frames in 0:01:16.27 (1.27 fps), 468.51 kb/s, Avg QP:36.60

Start:    20:22:32
End:      20:23:50
Duration: 00:01:17

HEVC : 240 KiB1184*664 (16:9), at 24.000 FPS, HEVC (Main 10@L3.1@Main), HDR10+
```

**Comment by kliffgomel** [comment]
> 
> 
> Could you please test [x265-x64-v3.4+62-aMod-gcc10.2.1-hdr10-info.exe.zip](https://github.com/staxrip/staxrip/files/5844273/x265-x64-v3.4%2B62-aMod-gcc10.2.1-hdr10-info.exe.zip)?

seems to work.

**Comment by kliffgomel** [comment]
This option either works or not. I think the problem has been resolved.

**Comment by 44vince44** [comment]
OK then, well done again @DJATOM  and thanks !!

**Comment by Dendraspis** [comment]
@44vince44 


> 
> 
> Could you please test [x265-x64-v3.4+62-aMod-gcc10.2.1-hdr10-info.exe.zip](https://github.com/staxrip/staxrip/files/5844273/x265-x64-v3.4%2B62-aMod-gcc10.2.1-hdr10-info.exe.zip)?

@stax76 
So you should take this one for the next beta.

**Comment by Patman86** [comment]
> @Patman86 I'm surprised of your silence... Are you drowning under work as well??? 😅 
> 

You're right, I can still go to work because my company is systemically relevant.  I mostly use the weekend.  With x265 I still have a problem with the manifest that doesn't work as hoped.

**Comment by 44vince44** [comment]
@Patman86 AH work, yes! I'm relieved that it's not related to your newly born child 😃 

Well I'm sure you'll get this working soon 😉

**Comment by Patman86** [comment]
Done, new version online.
