### ISSUE TITLE
Script exceeded memory limit.  Memory leak?

### ISSUE THREAD

**Issue by Neltulz** [staxrip/staxrip#470]
Using Staxrip version 2.1.6.0

**Describe the bug**
I exceeded my physical ram of 64GB, and my commit exceeded 157GB
![2021-01-22_02-01-56](https://user-images.githubusercontent.com/7741742/105463847-43d66900-5c56-11eb-9ab1-5fdf46487438.png)

Paused here:
![image](https://user-images.githubusercontent.com/7741742/105464631-80ef2b00-5c57-11eb-8c5f-980bf68cf0aa.png)

**Expected behavior**
Encode a movie successfully without error and hopefully without extreme memory usage.

**How to reproduce the issue**
1. Get some 4K movie footage.  In my case, Red October 4K
2. Create an .ASS subtitle file for the movie
3. switch to Vaporsynth
4. add a hardcoded subtitle (the .ass file)
5. Be sure to use core.sub.TextFile as the renderer
6. auto crop the movie to remove black bars
7. use x265
8. quality: 17
9. preset: medium
10. tune: grain
11. container: mkv
12. audio: none
13. Cut the movie into 8 roughly equal parts using the preview window (probably unnecessary) to recreate the bug
14. Start the job list
15. Watch the memory usage reach the sky.
16. I made it to about 32.5% (7924/24364 frames) before cpu usage died completely due to total exhaustion of ram and page file

**Log BEFORE aborting**
[hunt_red_october_4k_hdr_10bit_0-24363_staxrip.log](https://github.com/staxrip/staxrip/files/5854366/hunt_red_october_4k_hdr_10bit_0-24363_staxrip.log)

**log AFTER aborting**
[hunt_red_october_4k_hdr_10bit_0-24363_staxrip_after_aborting.log](https://github.com/staxrip/staxrip/files/5854389/hunt_red_october_4k_hdr_10bit_0-24363_staxrip_after_aborting.log)

**Comment by JJKylee** [comment]
This memory leak issue is resolved in the latest beta version.
See [this](https://github.com/staxrip/staxrip/issues/445).

**Comment by Neltulz** [comment]
> This memory leak issue is resolved in the latest beta version.
> See [this](https://github.com/staxrip/staxrip/issues/445).

Nice! Thank you!

**Comment by JJKylee** [comment]
You better replace your current `x265.exe` file with @DJATOM's most recent build: [here](https://github.com/staxrip/staxrip/issues/464#issuecomment-763819976).
This version fixes: AVS `--seek` issue, vpy memory leak/heap corruption issues, UTF-8 input issue, and lack of `--dhdr10-info` option support.

Remember, only @DJATOM's mod version (and now @Patman86's mod version as well) supports direct `avs`/`vpy` input and other various functions requested by StaxRip for `x265`, and it's _very recent_ that this was made possible. I'd like to recommend you always keep up with the most recent beta release and follow related issues on this repo. 😄

**Comment by Neltulz** [comment]
> You better replace your current `x265.exe` file with @DJATOM's most recent build: [here](https://github.com/staxrip/staxrip/issues/464#issuecomment-763819976).
> This version fixes: AVS `--seek` issue, vpy memory leak/heap corruption issues, UTF-8 input issue, and lack of `--dhdr10-info` option support.
> 
> Remember, only @DJATOM's mod version (and now @Patman86's mod version as well) supports direct `avs`/`vpy` input and other various functions requested by StaxRip for `x265`, and it's _very recent_ that this was made possible. I'd like to recommend you always keep up with the most recent beta release and follow related issues on this repo. 😄

Solid advice, but I can't always follow related issues.  My heart's just not in it.  Time is precious.

I updated to the latest Staxrip v2.1.7.3-beta.  There still appears to be a massive memory leak.  I'm 24% through and I'm back up to 90GB commited, and all 55/64GB of physical memory used.

I'm going to abort and try updating x265 as you suggested.  I am really annoyed by this. Hopefully a stable version of StaxRip can come out that resolves this issue so that I don't have to resort to Beta versions of x265 and manually updating x265.

In all the time I've used StaxRip, it has never been this riddled with issues.  It has always been a quality GUI, devoid of major issues.  I guess those days are long gone.

**Comment by DJATOM** [comment]
Does vspipe "leaks" as well? 6700k is 8 threads, you can try to limit requests to 4 and see if it still present.

**Comment by Neltulz** [comment]
Okay, x265 updated.  I am keeping a watchful eye on memory usage.

![image](https://user-images.githubusercontent.com/7741742/105478289-a173b100-5c68-11eb-9136-58cc02801498.png)


> Does vspipe "leaks" as well? 6700k is 8 threads, you can try to limit requests to 4 and see if it still present.

No idea.

**Comment by DJATOM** [comment]
I tested with 1080p video and 24 threads (Ryzen 3900x user here) and didn't encountered any leaks. Memory usage was near expected values. But with 4k videos memory usage will rise significantly.

**Comment by Neltulz** [comment]
> I tested with 1080p video and 24 threads (Ryzen 3900x user here) and didn't encountered any leaks. Memory usage was near expected values. But with 4k videos memory usage will rise significantly.

To be honest, I haven't been keeping a close eye on memory usage until my computer started suffering instability.  So, I actually have no idea how much typical memory usage is for 4K movies.

In other words, I have no point of reference.  I don't know what ideal memory usage looks like for 4k conversion.  But something tells me, it shouldn't be anywhere near 64GB of physical memory, and 100GB of commit.

**Comment by DJATOM** [comment]
I'll download that movie and try to reproduce on my end. Already googled uhd remux of this.

**Comment by DJATOM** [comment]
Speed is no so fast, only 2 seeds. It might take day or two...

**Comment by Neltulz** [comment]
[hunt_red_october_4k_hdr_10bit.ass.zip](https://github.com/staxrip/staxrip/files/5855200/hunt_red_october_4k_hdr_10bit.ass.zip)

Here is the ass subtitle I created for it.  I used aegisub to create it.

**Comment by DJATOM** [comment]
Thanks, speed got better btw. Now it's 5 hours eta to download.

**Comment by Neltulz** [comment]
Yeah, I am getting a warning now.  "Script exceeded memory limit.  Consider raising cache size."

I have no idea why this is happening.  I've converted other movies, but not had this issue.  To give you an idea, I converted the LOTR 4k trilogy with hardcoded subtitles, the very same way.

I believe I used.... Staxrip v2.1.3.0 Stable for that.

If these issues persist, I may have no choice but to go back to that.

**Comment by Dendraspis** [comment]
The only big change is that the used input: pipe vs. direct input.

What happens it you select ***PIPE = VSPIPE*** instead of *none* in the x265 options ?

This would help a lot.

**Comment by Neltulz** [comment]
> The only big change is that the used input: pipe vs. direct input.
> 
> What happens it you select _**PIPE = VSPIPE**_ instead of _none_ in the x265 options ?
> 
> This would help a lot.

Okay I have changed it to VSPIPE.  Here we go.  I will report back with results.

**Comment by Neltulz** [comment]
> Does vspipe "leaks" as well? 6700k is 8 threads, you can try to limit requests to 4 and see if it still present.

I guess if I would've asked what vspipe was, I could've avoided further confusion on this issue.

Sorry for wasting everyone's time.

**Comment by JJKylee** [comment]
> I guess if I would've asked what vspipe was, I could've avoided further confusion on this issue.
> 
> Sorry for wasting everyone's time.

Oh, you don't have to be. At least we've found there's something with `x265` in regards to _direct_ `vpy` input.
I think @DJATOM will come up with a solution as he always has. 😄

**Comment by Neltulz** [comment]
It is a huge relief that my memory is back under control now.  Thanks everyone for your help.

**Comment by DJATOM** [comment]
![изображение](https://user-images.githubusercontent.com/4888694/105484791-99416300-5cb4-11eb-8d20-7de098dd7d8c.png)
Testing...

**Comment by Neltulz** [comment]
I am jealous of that framerate.

**Comment by Patman86** [comment]
@DJATOM I think we should try to take the solution from rigaya or from vspipe. I started doing it once, but then moved away from it.

**Comment by DJATOM** [comment]
I'd like to upgrade to 5950X, maybe in the future.

As for leak, I don't see any major leak on my side. memory usage is near 7800 MB and staying at that for the whole encoding (I just tested on cut I managed to download, it's near 4300 frames).

**Comment by Neltulz** [comment]
> I'd like to upgrade to 5950X, maybe in the future.
> 
> As for leak, I don't see any major leak on my side. memory usage is near 7800 MB and staying at that for the whole encoding (I just tested on cut I managed to download, it's near 4300 frames).

My issue resolved once I set Pipe to VSPIPE in x265.  Are you using Pipe = None?

**Comment by DJATOM** [comment]
yes, I tried with Pipe = None and there was no leak on my side. But I didn't split onto chunks, maybe that matters.

**Comment by DJATOM** [comment]
![изображение](https://user-images.githubusercontent.com/4888694/105487935-9137f200-5cb9-11eb-9b5a-da7ef3d0ec50.png)
I set 8 chunks and memory usage indeed high. So I believe it's not a leak, but misuse/bad combination of options. Maybe it's good to limit requests (by adding constraint into generated chunk scripts), that will help with abnormal memory usage.

**Comment by Neltulz** [comment]
That's not the way I'm splitting the video.

![image](https://user-images.githubusercontent.com/7741742/105488664-970ce380-5c77-11eb-967c-2b87cb7bce99.png)

I have basically manually created 8 separate cuts, and I'm running only 1 job at a time.

The reason I'm doing this is, if my computer turns off due to a power outage, or my computer crashes for some mysterious reason (perhaps a video game causes my computer to crash).... then I will only lose that one job, as opposed to the entire movie.

**Comment by DJATOM** [comment]
Ah, so you had that leak on a single chunk? 
![изображение](https://user-images.githubusercontent.com/4888694/105489099-5f278f80-5cbb-11eb-9cdd-6e3188270305.png)
How much `x265` tabs staxrip displays at the time of encoding?

**Comment by Neltulz** [comment]
![image](https://user-images.githubusercontent.com/7741742/105489233-8a3cbf80-5c78-11eb-9b5d-f7c7bc690422.png)

**Comment by DJATOM** [comment]
Definitely weird and should never happen. Too bad I can't reproduce it to fix.

**Comment by Neltulz** [comment]
> Definitely weird and should never happen. Too bad I can't reproduce it to fix.

Yeah, I don't understand it.

Question:  Since I created the .srip project in StaxRip v2.1.6.0-stable, and then I opened that same project on v2.1.7.3-beta, could that explain some problems?

**Comment by Dendraspis** [comment]
Just a side note:
I used v2.1.7.0 a lot without pipe on 2160p material and I have absolutely no issues recognized with AVS. Seems to be a pure VPY issue. 🤔

**Comment by Dendraspis** [comment]
> Question:  Since I created the .srip project in StaxRip v2.1.6.0-stable, and then I opened that same project on v2.1.7.3-beta, could that explain some problems?

This can create issues, but it should not be responsible for this one. 🤔

**Comment by Neltulz** [comment]
Perhaps I will clip a short sample of my particular MKV remux, and then I will record my screen demonstrating step by step what I did... on a fresh StaxRip, with a fresh project.

It will have to be tomorrow.  I can't do it tonight.

**Comment by DJATOM** [comment]
Compared vspipe+x265 against direct input (using 8 VS threads, near 1000 frames encoded): 5795 MB vs 5929 MB. 134 MB is most likely the size of temp buffer used to copy frames from VS to x265 (x265 3.4 requirement). No matter how much I try, I can't reproduce. Maybe will try rigaya's solution when I'ill have a time for proper development.

**Comment by Dendraspis** [comment]
@DJATOM 
Is it possible, that the buffer won't be released (completely) under some circumstances? 🤔
This could explain the slow increase of memory usage - maybe it helps.

**Comment by DJATOM** [comment]
I think there is no issue with those temp buffers, it's released once frame consumed by x265. But callback code use some trick to request more frames when frame queue is full but consumer (readPicture) still can't fetch desired frame from frame map. For now I'm doubting that place might be a culprit (for example, with 8 threads and 4k footage there's better chances that frames will be processed out of order and that hack leading to abnormal extra requests. I have to install virtual machine to reproduce environment with 8 threads, I'll try that when will have a time. Want to finish work stuff first.

**Comment by Neltulz** [comment]
@DJATOM,

I have recorded a demonstration video and included the files used.  Please try reproducing the bug with these files. :)

https://www.dropbox.com/s/26u71gi08jo2sqg/staxrip_v2-1-7-3-beta_x265_memory_issue.7z?dl=0

Currently uploading that to Dropbox.  ETA: 20minutes approx.

**Comment by DJATOM** [comment]
[x265-x64-v3.4+62-aMod-gcc10.2.1.exe.zip](https://github.com/staxrip/staxrip/files/5861154/x265-x64-v3.4%2B62-aMod-gcc10.2.1.exe.zip)

Measured RAM usage encoding your sample at near 1500 frames
VSPipe + x265: 3276+ 2513 = 5789 MB
x265: 5568 MB
Mostly the same speed here, but I didn't measured full encoding to properly compare.

I have changed the logic of frame prefetching. Earlier it issued new async requests from callback, but now it's moved to "consumer" part. Also now I'm using WaitForSingleObject and SetEvent to signal when frame is produced and can be taken for encoding. I tried with rigaya's method, unfortunately it's not working or I'm to dumb for it (but I think I got the idea). 
It might be slower with super heavy scripts (where script processing is the bottleneck) but indeed fast and mostly non-blocking with simple scripts. I'll publish new commit if it passes community testing.

**Comment by Neltulz** [comment]
Thanks! I will do more extensive testing when I get the time. :)

For now, VSPIPE resolved the issue nicely.

Thanks for your help.

**Comment by Dendraspis** [comment]
@DJATOM 
Had an example and tested it. Before it started at around 4GB RAM and after a few minutes it reached 20GB and climbing.
Then I tested the same StaxRip instance with changed `x265.exe` and the memory usage is at about 4.8GB. After ~1100 frames it's still below 4.95GB and going few kb up and down.
So it seems to work now.  🥳

**Comment by DJATOM** [comment]
Wellm now I'm drunk and can't do much om clean-up code and push. Will take care on it tomorrow after work.

**Comment by 44vince44** [comment]
Will work keep you from getting drunk again ?? 🤣   😁

**Comment by DJATOM** [comment]
I think the beer is wearing out already, testing compilation on linux and adjusting code to support linux as well.

**Comment by DJATOM** [comment]
![изображение](https://user-images.githubusercontent.com/4888694/105621193-b0e02f00-5e0d-11eb-8031-9e9042f50f53.png)
Looks like my linux box eat that well, so will clean up the code and arrange the commit.

**Comment by DJATOM** [comment]
@44vince44 I got the payment yesterday, so bought some beer. Usually I'm not into drinking but at rare occasions it's nice to relax. I'm freelancer, so there is no weekend for me usually...

**Comment by 44vince44** [comment]
@DJATOM I am a freelancer too ;-) I know exactly what you're talking about 🤣

**Comment by Dendraspis** [comment]
@DJATOM 
> Looks like my linux box eat that well, so will clean up the code and arrange the commit.

Just for your information - didn't want to open an issue for that:
Yesterday released `3.4+65-aMod` indicates itself as `x265 3.4+62-aMod-gcc10.2.1+opt msg7086/DJATOM`:

![XXX](https://user-images.githubusercontent.com/50659978/105705419-79a67680-5f10-11eb-8a44-783c72bc62ae.JPG)

**Comment by DJATOM** [comment]
But its 65! I think its due to older ma10/ma12 libs. Does 8 bit lib ahow 65?

**Comment by Neltulz** [comment]
I just downloaded 65 and I am using the skylake build.

Appears to be reporting as: ``x265 [info]: HEVC encoder version 3.4+65-2ce978dd9 [DJATOM's Mod]``

![image](https://user-images.githubusercontent.com/7741742/105707713-f4539f80-5ed8-11eb-9176-33075916aea2.png)

**Comment by Dendraspis** [comment]
@DJATOM 
Yes, I know - therefore I attached the screenshot that shows a working `--reader-options library` with AVS. 

And yes, 8bit shows the correct version:
![XXX2](https://user-images.githubusercontent.com/50659978/105707985-10286700-5f14-11eb-84ec-618e7b3064bc.JPG)

**Comment by DJATOM** [comment]
Literally this affects nothing, since 10/12 libs didn't changed with that commit distance. But ok, I'll rebuild it for consistency.

**Comment by DJATOM** [comment]
@Neltulz So new frame prefetching startegy works for you?

**Comment by Neltulz** [comment]
@Neltulz So new frame prefetching strategy works for you?

Ahh, I should probably test that. lol  Let me get back to you on that.

Also @DJATOM, I really like the extra information on the status line.

**Comment by Dendraspis** [comment]
> Also @DJATOM, I really like the extra information on the status line.

I like them, too! A lot!!
For those with low res displays or little space I already got a StaxRip solution that [has to be tested yet](https://github.com/staxrip/staxrip/discussions/480).

**Comment by Neltulz** [comment]
Okay I am testing v65 now with pipe:none on the red october 4k movie.  Memory usage seems stable so far!

![image](https://user-images.githubusercontent.com/7741742/105709412-4c8ba100-5edb-11eb-951f-59a92e2ee097.png)

**Comment by Neltulz** [comment]
@DJATOM do you have Paypal? I do not do any form of bitcoin mining so I can't donate that way.

**Comment by DJATOM** [comment]
I have a friend with paypal and hardware btc wallet (in profile description). Paypal doesn't work in Ukraine. Write me into djatom@beatrice-raws.org to discuss that if you want 😌

**Comment by Dendraspis** [comment]
@DJATOM 
Didn't expect a fix for the current release. I hoped the next release would be fixed to prevent confusion.  😄 

***Works like a charm, thanks!***  🥳   

![XXX4](https://user-images.githubusercontent.com/50659978/105722983-8df56e00-5f26-11eb-9e1e-e65c30286272.JPG)

**Comment by Neltulz** [comment]
@DJATOM I don't know if it matters to you, but I fixed up that .ASS subtitle.  I noticed the text was desynced from the audio, so I shifted the text to better sync.  I fixed the resolution and placement.  I improved the text brightness.  I removed some unnecessary subs for english speaking parts.

I now consider this perfect.   So, if you felt like hardcoding these subtitles into your Red October, go right ahead. :)

[hunt_red_october_4k_hdr_10bit_FIXED.ass.zip](https://github.com/staxrip/staxrip/files/5870686/hunt_red_october_4k_hdr_10bit_FIXED.ass.zip)

**Comment by DJATOM** [comment]
Sure. I downloaded it for vpy tests, but might consider to actually watch it. Thanks for the share 😎

**Comment by 44vince44** [comment]
It's a wonderful film in the directing, actors and acting aspects, but those films always have an underlying political propaganda (sadly)...

**Comment by Neltulz** [comment]
> It's a wonderful film in the directing, actors and acting aspects, but those films always have an underlying political propaganda (sadly)...

Yeah, murika good, russia bad... etc etc.

**Comment by Dendraspis** [comment]
After some investigating ***"Script exceeded memory limit. Consider raising cache size."*** is not causing or caused by the memory leak. 

To prevent this warning message you have to set [max_cache_size](http://vapoursynth.com/doc/pythonreference.html?highlight=max_cache_size#Core.max_cache_size) to free the memory more aggressively. This is interesting, because by default it seems to be set to 1GB on 32bit and 4GB on 64bit systems. 

Using *vspipe* there was no warning message during my encodes, probably because of the default setting?!
Using *Direct Input* there is a warning message, unless you specify this parameter - even 4GB was okay for me and the warning message was gone: 
`core.max_cache_size = 4096`

Maybe it can help somebody...

**Comment by DJATOM** [comment]
Normally VS reusing "released" buffers rather than explicitly freeing memory and then allocating new (since allocate/free operations are time-consuming), but if there's not much released buffers, it will try to aggressively free until we'll fit into allowed size - [vscore.cpp#L428](https://github.com/vapoursynth/vapoursynth/blob/d2f6cb0294e725605e8d86596172f3e638de7435/src/core/vscore.cpp#L428). Since We allow up to `threads` number of frames to be available for consuming by x265, it also counts as not "released" memory for VS, thus warning is  triggered if we've reached the border.

**Comment by Dendraspis** [comment]
Indeed, but x265, as a process, doesn't seem to need significantly more or less memory with or without this setting. Even though the default should be the same the question seems to be:
Is the default value (4GB) really applied or is a much lower value used, for example 1GB?

In my use ases the message only appears if I use a filter. Passing through and cropping works without issue.

This being said: Even with the message x265 works great and doesn't need more than roughly 4-6GB RAM. So the memory leak is gone, we are just talking about that cache size limit.

**Comment by DJATOM** [comment]
4GB is just a hard limit, until that point buffers will be reused if possible or allocated new if it's not enough. 
Btw, avs+'s memory allocation works similar way. For plugin writers there [some API](https://github.com/AviSynth/AviSynthPlus/blob/master/avs_core/core/avisynth.cpp#L1307) exists to reuse internal buffers (with flag AVS_POOLED_ALLOC). That will save time on allocation if plugin allocating the same amount of memory on each frame (and uses generic allocation if there's no fitting buffer available).

**Comment by Dendraspis** [comment]
Yeah, but why there is no message with vspipe and its 4GB default whereas x265 with direct input set to 4096MB shows it?
Assuming that vspipe would print it so StaxRip would catch it.

**Comment by DJATOM** [comment]
> why there is no message with vspipe
Try cmd, I have triggered that warning with 4k and hardsubbing in cmd.

**Comment by Dendraspis** [comment]
I'll try it later.

In my case the message appeared on a cropped 1080p content with Degraining filter. 🤔

**Comment by Dendraspis** [comment]
Okay, I tried, but couldn't reproduce my observations  - there was no difference between both methods.  😲 
I'll try to have a look on it and report again if it occurs. But I believe the used source and filters were right at the limit border so it needed only ~1MB'ish to exceed the limit. 🤔 

So in conclusion:
The default cache size for 64bit systems is ***4GB*** and can be set via [max_cache_size](http://vapoursynth.com/doc/pythonreference.html?highlight=max_cache_size#Core.max_cache_size)
`core.max_cache_size = 4096`  in megabytes.
