### ISSUE TITLE
2.1.7.5: Arguments for preprocessor 'ffmpeg: Re-mux TS to MKV' should be modified

### ISSUE THREAD

**Issue by JJKylee** [staxrip/staxrip#483]
**Describe the bug**

When `aac` muxing mode is `ADTS` in the audio track of a source `ts` file, (pretty common for a `ts` file), the current preprocessor `ffmpeg: Re-mux TS to MKV` **_fails to remux the audio track_** into the output `mkv` file with the following error message (ffmpeg):

```
[mpegts @ 000002521d679e00] start time for stream 1 is not set in estimate_timings_from_pts
[mpegts @ 000002521d679e00] stream 1 : no TS found at start of file, duration not set
[mpegts @ 000002521d679e00] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 0 channels): unspecified sample format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```

**Suggested fix**

Per the recommendation given by the log, the **_arguments_** of the preprocessor should be modified as follows:

```
-analyzeduration 100M -probesize 50M -i "%source_file%" -c copy -ignore_unknown -sn -y -hide_banner "%temp_file%.mkv"
```

**Comment by 44vince44** [comment]
Although it never happened to me, i concur !

**Comment by JJKylee** [comment]
Maybe it was too short.

Reproducing this issue is simple.

Download `LG New York HDR UHD 4K Demo.ts` from [4kmedia.org](https://4kmedia.org/lg-new-york-hdr-uhd-4k-demo/) and load it in the original _non-modded_ version of 2.1.7.5 (with `ffmpeg: Re-mux TS to MKV`). You'll see this 'no audio' `mkv`.

![StaxRip_2 1 7 5_no-audio_with_default_ffmpeg-mkv-remuxer_arguments_20210131](https://user-images.githubusercontent.com/3157518/106379540-918f5780-6361-11eb-9fcd-4435fde7dc9c.jpg)

With `-analyzeduration 100M -probesize 50M` added to the arguments, `ffmpeg` catches audio in the output `mkv` file as follows:

![StaxRip_2 1 7 5_audio_with_modified_ffmpeg-mkv-remuxer_arguments_20210131](https://user-images.githubusercontent.com/3157518/106379598-e501a580-6361-11eb-953b-6ca23edae92a.jpg)

Hope this helps.

**Comment by 44vince44** [comment]
There are other issues related to audio stream identification that are solved with -analyzeduration 100M -probesize 50M.
I can't remember on what occasion I read about that (it was several months ago) but I do remember that you can safely add those for all ts->mkv preprocessing operations safely: if those arguments are not necessary, then they will cause no harm.

**Comment by Dendraspis** [comment]
> I can't remember on what occasion I read about that (it was several months ago)

***The same procedure as every year, James*** 😜
 https://github.com/staxrip/staxrip/issues/149

**Comment by JJKylee** [comment]
I admit I was a little mistaken in regards to the `-bsf` part. It isn't necessary for `mkv`. Unlike back then, the only thing we need for `mkv` conversion is the extra options in the arguments. We don't need to add another preprocessor. So the same issue was not resolved appropriately back then. 😄

**Comment by Dendraspis** [comment]
The question is:  How high should those values be?  Is 100M/50M high enough? Or maybe too high? And who else uses this piece of **** expect @JJKylee ?   🤔 

*Feels like an X-Files moment.* 🤣

**Comment by Dendraspis** [comment]
`analyzeduration` 's default is 5,000,000 or 5000M = 5 seconds
`probesize` 's default is 5,000,000 or 5000M

@JJKylee 
Could you verify if only setting `probesize=2M` would also fix the issue?

**Comment by JJKylee** [comment]
For `analyzeduration`, 100M means 100 seconds = 1 min 40 seconds. The value itself can be adjusted, of course. For `probesize`, 50M means 50 MB, and since it's the default value, we don't need to add it explicitly unlike `analyzeduration`.

I really don't know why no one else is talking about this matter. Maybe they don't use `mkv` conversion at all or they don't work on `ts` files with `ADTS` aac tracks...?

**Comment by Dendraspis** [comment]
> EDIT: The default value for probesize is 5M, not 50MB. (I was typing on iPad... 😓)

I made the same mistake. 😄 
So it seems like the default values are too low to fetch the whole pattern in some ADTS-AAC-tracks.

> And I've found that just by setting `-probesize 10M`, the missing audio issue is gone. 😄

👍 

> (I've been using both `-analyzeduration 100M` and `-probesize 50M` habitually since they don't hurt performance significantly. 😝)

I'll try to set the missing parameter(s) ...

**Comment by Dendraspis** [comment]
Okay, now the args looks like:
`-i "%source_file%" -c copy -ignore_unknown -probesize=10M -sn -y -hide_banner "%temp_file%.mkv"`

Set it manually or delete your settings to make use of it. Will be implemented in the next beta.

**Comment by JJKylee** [comment]
`-probesize` is an **input** option, so in theory, it should be placed _before_ `-i`, not after.

**Comment by Dendraspis** [comment]
***ffmpeg-parameter-mode engaged***

🤣  You're absolutelly right!  It's fixed and looks like:
`-probesize 10M -i "%source_file%" -c copy -ignore_unknown -sn -y -hide_banner "%temp_file%.mkv"`
Thanks for shouting!  👍 

***NVEnc-subparameter-mode re-engaged*** 😁
